In [1]:
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline


data = pd.read_csv("ga_labeled.csv")
data.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>blockID</th>
      <th>txID</th>
      <th>seq</th>
      <th>addrID</th>
      <th>sum</th>
      <th>block_timestamp</th>
      <th>balance</th>
      <th>n_inputs</th>
      <th>n_outputs</th>
      <th>n_txs</th>
      <th>cluster</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>-1.782753</td>
      <td>-1.753375</td>
      <td>-0.140317</td>
      <td>-0.514563</td>
      <td>-2.199304</td>
      <td>-1.733706</td>
      <td>0.261965</td>
      <td>-0.221446</td>
      <td>-0.107145</td>
      <td>-0.216222</td>
      <td>2</td>
    </tr>
    <tr>
      <th>2</th>
      <td>-1.782753</td>
      <td>-1.753378</td>
      <td>-0.140317</td>
      <td>-0.514563</td>
      <td>-0.598916</td>
      <td>-1.733706</td>
      <td>0.444156</td>
      <td>-0.221446</td>
      <td>-0.107145</td>
      <td>-0.216222</td>
      <td>2</td>
    </tr>
    <tr>
      <th>3</th>
      <td>-1.782753</td>
      <td>-1.753377</td>
      <td>-0.140317</td>
      <td>-0.514563</td>
      <td>-0.268953</td>
      <td>-1.733706</td>
      <td>0.424287</td>
      <td>-0.221446</td>
      <td>-0.107145</td>
      <td>-0.216222</td>
      <td>2</td>
    </tr>
    <tr>
      <th>4</th>
      <td>-1.782753</td>
      <td>-1.753378</td>
      <td>-0.140317</td>
      <td>-0.514563</td>
      <td>-2.202442</td>
      <td>-1.733706</td>
      <td>0.488375</td>
      <td>-0.221446</td>
      <td>-0.107145</td>
      <td>-0.216222</td>
      <td>2</td>
    </tr>
    <tr>
      <th>5</th>
      <td>-1.782753</td>
      <td>-1.752993</td>
      <td>-0.140317</td>
      <td>-0.911458</td>
      <td>0.000819</td>
      <td>-1.733706</td>
      <td>0.650967</td>
      <td>-0.192982</td>
      <td>-0.107145</td>
      <td>-0.216222</td>
      <td>2</td>
    </tr>
  </tbody>
</table>
</div>

In [2]:
print(data.shape)


(97816, 11)


In [3]:
print(data.groupby("cluster").size())


cluster
1     1886
2    95930
dtype: int64


In [4]:
features = list(data.columns)
print(features)

features.remove("cluster")
print(features)

['blockID', 'txID', 'seq', 'addrID', 'sum', 'block_timestamp', 'balance', 'n_inputs', 'n_outputs', 'n_txs', 'cluster']
['blockID', 'txID', 'seq', 'addrID', 'sum', 'block_timestamp', 'balance', 'n_inputs', 'n_outputs', 'n_txs']


In [5]:
x = data[features]
y = data["cluster"]




In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, 
                                                    y, 
                                                    test_size=0.30)

In [7]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


In [8]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import numpy as np

knn = KNeighborsClassifier(2)
knn.fit(X_train, y_train)
print('Accuracy of K-NN classifier on training set: {:.5f}'.format(
    knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.5f}'.format(
    knn.score(X_test, y_test)))
print(confusion_matrix(y_test, knn.predict(X_test)))


Accuracy of K-NN classifier on training set: 0.99986


Accuracy of K-NN classifier on test set: 0.99930


[[  489     3]
 [   14 23948]]


In [35]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)
print('Accuracy of GNB classifier on training set: {:.5f}'
      .format(gnb.score(X_train, y_train)))
print('Accuracy of GNB classifier on test set: {:.5f}'
      .format(gnb.score(X_test, y_test)))
print(confusion_matrix(y_test, gnb.predict(X_test)))


Accuracy of GNB classifier on training set: 0.95947
Accuracy of GNB classifier on test set: 0.95877
[[  589     0]
 [ 1210 27546]]


In [10]:
from sklearn.svm import SVC

svm = SVC(kernel="linear", C=0.025)
svm.fit(X_train, y_train)
print('Accuracy of SVM classifier on training set: {:.5f}'
      .format(svm.score(X_train, y_train)))
print('Accuracy of SVM classifier on test set: {:.5f}'
      .format(svm.score(X_test, y_test)))
print(confusion_matrix(y_test, svm.predict(X_test)))


Accuracy of SVM classifier on training set: 0.99975
Accuracy of SVM classifier on test set: 0.99955


[[  484     8]
 [    3 23959]]


In [11]:
svm2 = SVC(gamma=2, C=1)
svm2.fit(X_train, y_train)
print('Accuracy of SVM2 classifier on training set: {:.5f}'
      .format(svm2.score(X_train, y_train)))
print('Accuracy of SVM2 classifier on test set: {:.5f}'
      .format(svm2.score(X_test, y_test)))
print(confusion_matrix(y_test, svm2.predict(X_test)))


Accuracy of SVM2 classifier on training set: 0.99995


Accuracy of SVM2 classifier on test set: 0.99542


[[  384   108]
 [    4 23958]]


In [12]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(alpha=1)
mlp.fit(X_train, y_train)
print('Accuracy of MLP classifier on training set: {:.5f}'
      .format(mlp.score(X_train, y_train)))
print('Accuracy of MLP classifier on test set: {:.5f}'
      .format(mlp.score(X_test, y_test)))
print(confusion_matrix(y_test, mlp.predict(X_test)))


Accuracy of MLP classifier on training set: 0.99781
Accuracy of MLP classifier on test set: 0.99726
[[  425    67]
 [    0 23962]]


In [13]:
svm3 = SVC()
svm3.fit(X_train, y_train)
print('Accuracy of SVM3 classifier on training set: {:.5f}'
      .format(svm3.score(X_train, y_train)))
print('Accuracy of SVM3 classifier on test set: {:.5f}'
      .format(svm3.score(X_test, y_test)))
print(confusion_matrix(y_test, svm3.predict(X_test)))


Accuracy of SVM3 classifier on training set: 0.99988


Accuracy of SVM3 classifier on test set: 0.99959


[[  489     3]
 [    7 23955]]
